version: '3.8'

services:
  backend:
    build: .
    command: python aegis_backend/manage.py runserver 0.0.0.0:8000
    volumes:
      - ./aegis_backend:/app/aegis_backend
      - ./aegis_backend/core:/app/core
      - aegis_data:/var/lib/postgresql/data
      - static_volume:/app/static
    ports:
      - "8000:8000"
    environment:
      - DEBUG=1


  frontend:
    working_dir: /app/frontend
    command: npm run dev
    volumes:
      - ./frontend:/app/frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend

volumes:
  aegis_data:
  static_volume:


  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - backend
      - frontend
